// <auto-generated />
using System;
using JobOverview.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobOverview.Data.Migrations
{
    [DbContext(typeof(JobOverviewContext))]
    [Migration("20240715132234_JeuDeDonnées")]
    partial class JeuDeDonnées
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobOverview.Model.Filiere", b =>
                {
                    b.Property<string>("CodeFiliere")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CodeFiliere")
                        .HasName("PrimaryKey_CodeFiliere");

                    b.ToTable("Filières", (string)null);

                    b.HasData(
                        new
                        {
                            CodeFiliere = "BIOV",
                            Nom = "Biologie Végétale"
                        },
                        new
                        {
                            CodeFiliere = "BIOH",
                            Nom = "Bologie Humaine"
                        },
                        new
                        {
                            CodeFiliere = "BIOA",
                            Nom = "biologie animale"
                        });
                });

            modelBuilder.Entity("JobOverview.Model.Logiciel", b =>
                {
                    b.Property<string>("CodeLogiciel")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodeFiliere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CodeLogiciel")
                        .HasName("PrimaryKey_CodeLogiciel");

                    b.HasIndex("CodeFiliere");

                    b.ToTable("Logiciels", (string)null);

                    b.HasData(
                        new
                        {
                            CodeLogiciel = "GENOMICA",
                            CodeFiliere = "BIOH",
                            Nom = "Génomica"
                        },
                        new
                        {
                            CodeLogiciel = "ANATOMIA",
                            CodeFiliere = "BIOH",
                            Nom = "Anatomia"
                        });
                });

            modelBuilder.Entity("JobOverview.Model.Module", b =>
                {
                    b.Property<string>("CodeModule")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodeLogiciel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodeLogicielParent")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodeModuleParent")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CodeModule")
                        .HasName("PrimaryKey_CodeModule");

                    b.HasIndex("CodeLogiciel");

                    b.HasIndex("CodeModuleParent", "CodeLogicielParent");

                    b.ToTable("Modules", (string)null);

                    b.HasData(
                        new
                        {
                            CodeModule = "SEQUENCAGE",
                            CodeLogiciel = "GENOMICA",
                            Nom = "Séquencage"
                        },
                        new
                        {
                            CodeModule = "MARQUAGE",
                            CodeLogiciel = "GENOMICA",
                            CodeLogicielParent = "GENOMICA",
                            CodeModuleParent = "SEQUENCAGE",
                            Nom = "Marquage"
                        },
                        new
                        {
                            CodeModule = "SEPARATION",
                            CodeLogiciel = "GENOMICA",
                            CodeLogicielParent = "GENOMICA",
                            CodeModuleParent = "SEQUENCAGE",
                            Nom = "Séparation"
                        },
                        new
                        {
                            CodeModule = "ANALYSE",
                            CodeLogiciel = "GENOMICA",
                            CodeLogicielParent = "GENOMICA",
                            CodeModuleParent = "SEQUENCAGE",
                            Nom = "Analyse"
                        },
                        new
                        {
                            CodeModule = "POLYMORPGYSME",
                            CodeLogiciel = "GENOMICA",
                            Nom = "Polymorphisme génétique"
                        },
                        new
                        {
                            CodeModule = "VAR_ALLELE",
                            CodeLogiciel = "GENOMICA",
                            Nom = "Varaitions alletiques"
                        },
                        new
                        {
                            CodeModule = "UTILS_ROLES",
                            CodeLogiciel = "GENOMICA",
                            Nom = "utilisateurs et rôles"
                        },
                        new
                        {
                            CodeModule = "PARAMETRES",
                            CodeLogiciel = "GENOMICA",
                            Nom = "Paramètres"
                        },
                        new
                        {
                            CodeModule = "MICRO",
                            CodeLogiciel = "GENOMICA",
                            Nom = "Anatomie microscopique"
                        },
                        new
                        {
                            CodeModule = "PATHO",
                            CodeLogiciel = "GENOMICA",
                            Nom = "Anatomie pathologique"
                        },
                        new
                        {
                            CodeModule = "FONC",
                            CodeLogiciel = "GENOMICA",
                            Nom = "Anatomie fonctionnelle"
                        },
                        new
                        {
                            CodeModule = "RADIO",
                            CodeLogiciel = "GENOMICA",
                            Nom = "Anatomie radiologique"
                        },
                        new
                        {
                            CodeModule = "TOPO",
                            CodeLogiciel = "GENOMICA",
                            Nom = "Anatomie topographique"
                        });
                });

            modelBuilder.Entity("JobOverview.Model.Release", b =>
                {
                    b.Property<short>("NumeroRelease")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("NumeroRelease"));

                    b.Property<string>("CodeLogiciel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("DateTime");

                    b.Property<float>("NumeroVersion")
                        .HasColumnType("real");

                    b.HasKey("NumeroRelease")
                        .HasName("PrimaryKey_NumeroRelease");

                    b.ToTable("Releases", (string)null);
                });

            modelBuilder.Entity("JobOverview.Model.Version", b =>
                {
                    b.Property<float>("NumeroVersion")
                        .HasColumnType("real");

                    b.Property<string>("CodeLogiciel")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSortiePrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSortieReelle")
                        .HasColumnType("datetime2");

                    b.Property<int>("Millesime")
                        .HasColumnType("int");

                    b.HasKey("NumeroVersion")
                        .HasName("PrimaryKey_NumeroVersion");

                    b.HasIndex("CodeLogiciel");

                    b.ToTable("Versions", (string)null);

                    b.HasData(
                        new
                        {
                            NumeroVersion = 1f,
                            CodeLogiciel = "GENOMICA",
                            DateOuverture = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortiePrevue = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortieReelle = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Millesime = 2023
                        },
                        new
                        {
                            NumeroVersion = 2f,
                            CodeLogiciel = "GENOMICA",
                            DateOuverture = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortiePrevue = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortieReelle = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Millesime = 2024
                        },
                        new
                        {
                            NumeroVersion = 4.5f,
                            CodeLogiciel = "ANATOMIA",
                            DateOuverture = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortiePrevue = new DateTime(2022, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortieReelle = new DateTime(2022, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Millesime = 2022
                        },
                        new
                        {
                            NumeroVersion = 5f,
                            CodeLogiciel = "ANATOMIA",
                            DateOuverture = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortiePrevue = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortieReelle = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Millesime = 2023
                        },
                        new
                        {
                            NumeroVersion = 5.5f,
                            CodeLogiciel = "ANATOMIA",
                            DateOuverture = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortiePrevue = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Millesime = 2024
                        });
                });

            modelBuilder.Entity("JobOverview.Model.Logiciel", b =>
                {
                    b.HasOne("JobOverview.Model.Filiere", null)
                        .WithMany()
                        .HasForeignKey("CodeFiliere")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOverview.Model.Module", b =>
                {
                    b.HasOne("JobOverview.Model.Logiciel", null)
                        .WithMany()
                        .HasForeignKey("CodeLogiciel")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JobOverview.Model.Module", null)
                        .WithMany()
                        .HasForeignKey("CodeModuleParent", "CodeLogicielParent")
                        .HasPrincipalKey("CodeModule", "CodeLogiciel")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("JobOverview.Model.Version", b =>
                {
                    b.HasOne("JobOverview.Model.Logiciel", null)
                        .WithMany()
                        .HasForeignKey("CodeLogiciel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
